security:
  jwt:
    secret-key: rrrkkkvvvsercretrkarpiikeydsagea123321412553asdasgsadasgs123tasfasfsd23553
google:
  client-id: 859510131427-kt9qeh2juherf403na5fphrpkf2p1ttj.apps.googleusercontent.com
cloudinary:
  api_key: 435163952552961
  cloud_name: dbxpvyzxo
  api_secret: XH4fZZjgc1ovpS57a9T8PsuPaKA